services:
  db:
    image: mysql
    container_name: mysqdemo
    ports:
    - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    image:  rabbitmq:3.13-rc-management
    container_name: my_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  project:
    depends_on:
      - db
      - rabbitmq
    image: abc
    container_name: demo
    build: .
    ports:
      - 8089
